# Generated by Django 5.1.2 on 2024-11-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='updated_at',
        ),
    ]
