# Generated by Django 5.1.2 on 2024-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_contact_us_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('get_started_button_text', models.CharField(default='Get Started', max_length=50)),
                ('get_started_button_url', models.CharField(blank=True, max_length=200)),
                ('video_button_text', models.CharField(default='Watch Video', max_length=50)),
                ('video_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
    ]
