# Generated by Django 5.1.2 on 2024-11-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='Transform your business ideas into reality. We provide all the tools and resources to help startups launch, grow, and thrive in today’s fast-paced digital world. Our platform is designed to streamline your journey from concept to market, making every step easy and efficient'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='get_started_button_url',
            field=models.CharField(default='#about', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='eStartup', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=Y7f98aduVJ8'),
        ),
    ]
