# Generated by Django 5.1.2 on 2024-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_herosection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Icon class or name', max_length=50)),
                ('background_color', models.CharField(blank=True, help_text='CSS color value or class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
