# Generated by Django 5.1.2 on 2024-11-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_featurecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecard',
            name='background_color',
        ),
    ]
