# Generated by Django 5.1.2 on 2024-11-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_featurecard_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecard',
            name='order',
        ),
    ]
