# Generated by Django 5.1.2 on 2024-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='button_icon',
            field=models.CharField(default='fa-arrow-right', max_length=50),
        ),
    ]
