# Generated by Django 5.1.2 on 2024-11-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_aboutsection_button_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Services', max_length=50)),
                ('section_title', models.CharField(default='Our Services', max_length=200)),
                ('service_item_icon', models.CharField(default='fa-check-circle', max_length=50)),
                ('service_item_title', models.CharField(max_length=200)),
                ('service_item_description', models.TextField()),
            ],
        ),
    ]
