# Generated by Django 5.1.2 on 2024-11-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_servicesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesection',
            name='section_title',
        ),
        migrations.AddField(
            model_name='servicesection',
            name='section_title1',
            field=models.CharField(default='Our', max_length=200),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='section_title2',
            field=models.CharField(default='Services', max_length=200),
        ),
    ]
