# Generated by Django 5.1.2 on 2024-11-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_servicesection_section_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item_icon', models.CharField(default='fa-check-circle', max_length=50)),
                ('service_item_title', models.CharField(max_length=200)),
                ('service_item_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Services', max_length=50)),
                ('section_title1', models.CharField(default='Our', max_length=200)),
                ('section_title2', models.CharField(default='Services', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
    ]
