# Generated by Django 5.1.2 on 2024-11-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_servicecards_serviceheader_delete_servicesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceheader',
            old_name='section_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='serviceheader',
            old_name='section_title1',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='serviceheader',
            old_name='section_title2',
            new_name='title2',
        ),
    ]
