# Generated by Django 5.1.2 on 2024-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_servicecards_servicecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features_SectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-check', max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeturesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='FEATURES', max_length=50)),
                ('title1', models.CharField(default='Our', max_length=200)),
                ('title2', models.CharField(default='Features', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
