# Generated by Django 5.1.2 on 2024-11-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_features_sectioncard_feturesheader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeturesHeader',
            new_name='FeaturesHeader',
        ),
    ]
