# Generated by Django 5.1.2 on 2024-11-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_rename_feturesheader_featuresheader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features_SectionCard',
        ),
        migrations.DeleteModel(
            name='FeaturesHeader',
        ),
    ]
